server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: index-route
          uri: lb://index-service
          predicates:
            - Path=/api/index/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: item-route
          uri: lb://item-service
          predicates:
            - Path=/api/item/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: item-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}

jwt:
  token:
    pubKeyPath: E:\javaSE0805\rsa\rsa.pub
    cookieName: gmall-token

