server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
jwt:
  token:
    pubKeyPath: E:\javaSE0805\rsa\rsa.pub
    priKeyPath: E:\javaSE0805\rsa\rsa.pri
    secret: fgytdjhgfr345tyfgj
    cookieName: gmall-token
    expireTime: 30
